## Ejercicios gestión de nulos

#### El objetivo del ejercicio es identificar las columnas que contienen valores nulos y aplicar un proceso de imputación para manejarlos de manera adecuada.

In [7]:
import pandas as pd
import numpy as np

# Imputación de nulos usando métodos avanzados estadísticos
# -----------------------------------------------------------------------
from sklearn.impute import SimpleImputer
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer
from sklearn.impute import KNNImputer

# Librerías de visualización
# -----------------------------------------------------------------------
import seaborn as sns
import matplotlib.pyplot as plt
# Configuración
# -----------------------------------------------------------------------
pd.set_option('display.max_columns', None) # para poder visualizar todas las columnas de los DataFrames

In [8]:
df_nulos = pd.read_csv('archivos/world_data_full_apply.csv',index_col=0)

In [9]:
df_nulos.sample(20)

,country,density,abbreviation,agricultural_land,land_area,armed_forces_size,birth_rate,calling_code,capital/major_city,co2-emissions,cpi,cpi_change,currency-code,fertility_rate,forested_area,gasoline_price,gdp,gross_primary_education_enrollment,gross_tertiary_education_enrollment,infant_mortality,largest_city,life_expectancy,maternal_mortality_ratio,minimum_wage,official_language,out_of_pocket_health_expenditure,physicians_per_thousand,population,population_labor_force_participation,tax_revenue,total_tax_rate,unemployment_rate,urban_population,latitude,longitude,continent
174,East Timor,89.000,TL,25.6,14.874,2.0,29.42,670.0,Dili,495.000,145.38,2.6,USD,4.02,45.4,1.10,1.673540e+09,115.3,17.8,39.3,Dili,69.3,142.0,0.60,Portuguese,10.2,0.72,NaN,67.3,25.0,17.3,4.55,400.182,-8.874217,125.727539,Asia
11,The Bahamas,39.000,BS,1.4,13.880,1.0,13.97,1.0,"Nassau, Bahamas",1.786,116.22,2.5,NaN,1.75,51.4,0.92,1.282700e+10,81.4,15.1,8.3,"Nassau, Bahamas",73.8,70.0,5.25,English,27.8,1.94,389.482,74.6,14.8,33.8,10.36,323.784,25.034280,-77.396280,Central America
137,Peru,26.000,PE,18.5,NaN,158.0,17.95,51.0,Lima,57.414,129.78,2.1,PEN,2.25,57.7,0.99,2.268481e+11,106.9,70.7,11.1,Lima,76.5,88.0,1.28,Spanish,30.9,1.27,NaN,77.6,14.3,36.8,3.31,NaN,-9.189967,-75.015152,South America
12,Bahrain,2.239,BH,11.1,765.000,19.0,13.99,973.0,Manama,31.694,117.59,2.1,BHD,1.99,0.8,0.43,3.857407e+10,99.4,50.5,6.1,Riffa,77.2,14.0,NaN,Arabic,25.1,0.93,NaN,73.4,4.2,13.8,0.71,NaN,26.066700,50.557700,Asia
143,Russia,9.000,RU,13.3,NaN,NaN,11.50,7.0,Moscow,NaN,180.75,4.5,RUB,1.57,49.8,0.59,1.699877e+12,102.6,81.9,6.1,Moscow,72.7,17.0,0.53,Russian,36.4,4.01,NaN,61.8,11.4,46.2,4.59,NaN,61.524010,105.318756,Europe
147,Saint Vincent and the Grenadines,284.000,VC,25.6,389.000,NaN,14.24,1.0,Kingstown,220.000,109.67,2.3,XCD,1.89,69.2,NaN,8.253852e+08,113.4,23.7,14.8,Calliaqua,72.4,68.0,1.16,English,21.4,0.66,100.455,65.9,25.4,37.0,18.88,58.185,12.984305,-61.287228,Central America
55,Estonia,31.000,EE,23.1,45.228,6.0,10.90,372.0,Tallinn,16.590,122.14,2.3,EUR,1.59,51.3,1.14,3.138695e+10,97.2,69.6,2.1,Tallinn,78.2,9.0,3.14,Estonian,22.8,4.48,NaN,63.6,20.9,47.8,5.11,916.024,58.595272,25.013607,Europe
25,Bulgaria,64.000,BG,46.3,110.879,31.0,8.90,359.0,Sofia,41.708,114.42,3.1,BGN,1.56,35.4,1.11,8.600000e+10,89.3,71.0,5.9,Sofia,74.9,10.0,1.57,Bulgarian,47.7,4.03,NaN,55.4,20.2,28.3,4.34,NaN,42.733883,25.485830,Europe
169,Switzerland,219.000,CH,38.4,41.277,21.0,10.00,41.0,Bern,34.477,99.55,0.4,CHF,1.52,31.8,1.45,7.030824e+11,105.2,59.6,3.7,Z���,83.6,5.0,NaN,German,28.3,4.30,NaN,68.3,10.1,28.8,4.58,NaN,46.818188,8.227512,Europe
34,Chad,13.000,TD,39.7,NaN,35.0,42.17,235.0,N'Djamena,1.016,117.70,-1.0,XAF,5.75,3.8,0.78,1.131495e+10,86.8,3.3,71.4,N'Djamena,54.0,1140.0,0.60,French,56.4,0.04,NaN,70.7,NaN,63.5,1.89,NaN,15.454166,18.732207,Africa
109,Mauritius,626.000,MU,42.4,2.040,3.0,10.20,230.0,Port Louis,4.349,129.91,0.4,MUR,1.41,19.0,1.12,1.418044e+10,101.1,40.6,13.6,Port Louis,74.4,61.0,0.38,French,50.7,2.53,NaN,58.3,19.1,22.2,6.67,515.980,-20.348404,57.552152,Africa
106,Malta,1.380,MT,32.4,316.000,2.0,9.20,356.0,Valletta,1.342,113.45,1.6,EUR,1.23,1.1,1.36,1.478616e+10,105.0,54.3,6.1,Birkirkara,82.3,6.0,5.07,Maltese,37.1,2.86,502.653,56.5,26.2,44.0,3.47,475.902,35.937496,14.375416,Europe
40,Costa Rica,100.000,CR,34.5,51.100,10.0,13.97,506.0,San Jos������,8.023,128.85,2.1,CRC,1.75,54.6,0.98,6.177394e+10,113.3,55.2,7.6,San Jos������,80.1,27.0,1.84,Spanish,21.5,2.89,NaN,62.1,13.6,58.3,11.85,NaN,9.748917,-83.753428,Central America
63,Georgia,57.000,GE,34.5,69.700,26.0,13.47,995.0,Tbilisi,10.128,133.61,4.9,GEL,2.06,40.6,0.76,1.774320e+10,98.6,63.9,8.7,Tbilisi,73.6,25.0,0.05,Georgian,57.3,7.12,NaN,68.3,21.7,9.9,14.40,NaN,42.315407,43.356892,Europe
33,Central African Republic,8.000,CF,8.2,622.984,8.0,35.35,236.0,Bangui,297.000,186.86,37.1,NaN,4.72,35.6,1.41,2.220307e+09,102.0,3.0,84.5,Bangui,52.8,829.0,0.37,French,39.6,0.06,NaN,72.0,8.6,73.3,3.68,NaN,6.611111,20.939444,Africa
158,Slovenia,103.000,SI,30.7,20.273,7.0,9.40,386.0,Ljubljana,12.633,111.05,1.6,EUR,1.60,62.0,1.32,5.374216e+10,100.4,78.6,1.7,Ljubljana,81.0,7.0,5.25,Slovene language,12.5,3.09,NaN,58.4,18.6,31.0,4.20,NaN,46.151241,14.995463,Europe
80,Iraq,93.000,IQ,21.4,438.317,209.0,29.08,964.0,Baghdad,190.061,119.86,0.4,IQD,3.67,1.9,0.61,2.340940e+11,108.7,16.2,22.5,Baghdad,70.5,79.0,1.24,Arabic,76.5,0.71,NaN,43.0,2.0,30.8,12.82,NaN,33.223191,43.679291,Asia
144,Rwanda,525.000,RW,73.4,26.338,35.0,31.70,250.0,Kigali,1.115,151.09,3.4,RWF,4.04,19.7,1.17,1.012247e+10,133.0,6.7,27.0,Kigali,68.7,248.0,NaN,Swahili,26.0,0.13,NaN,83.7,14.3,33.2,1.03,NaN,-1.940278,29.873888,Africa
115,Montenegro,47.000,ME,19.0,13.812,12.0,11.73,382.0,Podgorica,2.017,116.32,2.6,EUR,1.75,61.5,1.16,5.494737e+09,100.0,56.1,2.3,Podgorica,76.8,6.0,1.23,Montenegrin language,31.8,2.76,622.137,54.4,NaN,22.2,14.88,417.765,42.708678,19.374390,Europe
98,Liechtenstein,238.000,LI,32.2,160.000,NaN,9.90,423.0,Vaduz,51.000,NaN,NaN,CHF,1.44,43.1,1.74,6.552859e+09,104.7,35.6,NaN,Schaan,83.0,NaN,NaN,German,NaN,NaN,38.019,NaN,NaN,21.6,NaN,5.464,47.141039,9.520935,Europe

In [10]:
df_nulos.style.highlight_null(color='pink')

Palestina tiene muchos nulos, podemos hacer un dropna para eliminar esa fila entera

In [11]:
# Filtrar y eliminar la fila donde la columna 'country' tiene el valor 'Palestinian National Authority'
df_nulos = df_nulos[df_nulos['country'] != 'Palestinian National Authority']

Comprobamos se ha eliminado de manera correcta

In [12]:
df_nulos['Palestinian National Authority']

KeyError: 'Palestinian National Authority'

### Identificación de Valores Nulos: Identifica todas las columnas que contengan valores nulos en el DataFrame.

In [ ]:
df_nulos.isnull().sum()

country                                   0
density                                   0
abbreviation                              6
agricultural_land                         6
land_area                                29
armed_forces_size                        28
birth_rate                                5
calling_code                              0
capital/major_city                        2
co2-emissions                            11
cpi                                      19
cpi_change                               15
currency-code                            14
fertility_rate                            6
forested_area                             6
gasoline_price                           19
gdp                                       1
gross_primary_education_enrollment        6
gross_tertiary_education_enrollment      11
infant_mortality                          5
largest_city                              5
life_expectancy                           7
maternal_mortality_ratio                 13
minimum_wage                             44
official_language                         5
out_of_pocket_health_expenditure          6
physicians_per_thousand                   6
population                              155
population_labor_force_participation     18
tax_revenue                              25
total_tax_rate                           11
unemployment_rate                        18
urban_population                        149
latitude                                  1
longitude                                 1
continent                                 1
dtype: int64

Todas las columnas tienen nulos menos:

country                                   0
density                                   0

### Selección de Método de Imputación: 

Discute con tu compañera cuál sería la mejor estrategia para manejar los valores nulos en cada una de las columnas identificadas en el paso anterior.

In [ ]:
columnas_categoricas = df_nulos.select_dtypes(include='O')
columnas_categoricas

,country,abbreviation,capital/major_city,currency-code,largest_city,official_language,continent
0,Afghanistan,AF,Kabul,AFN,Kabul,Pashto,Asia
1,Albania,AL,Tirana,ALL,Tirana,Albanian,Europe
2,Algeria,DZ,Algiers,DZD,Algiers,Arabic,Africa
3,Andorra,AD,Andorra la Vella,EUR,Andorra la Vella,Catalan,Europe
4,Angola,AO,Luanda,AOA,Luanda,Portuguese,Africa
...,...,...,...,...,...,...,...
190,Venezuela,VE,Caracas,VED,Caracas,Spanish,South America
191,Vietnam,VN,Hanoi,VND,Ho Chi Minh City,Vietnamese,Asia
192,Yemen,YE,Sanaa,YER,Sanaa,Arabic,Asia
193,Zambia,ZM,Lusaka,ZMW,Lusaka,English,Africa
194,Zimbabwe,ZW,Harare,NaN,Harare,Shona,Africa

In [ ]:
# Obtenemos la lista de columnas categóricas que tienen nulos
nulos_categoricas = df_nulos[df_nulos.columns[df_nulos.isnull().any()]].select_dtypes(include = "O").columns
print("Las columnas categóricas que tienen nulos son : \n ")
print(nulos_categoricas)

Las columnas categóricas que tienen nulos son :

Index(['abbreviation', 'capital/major_city', 'currency-code', 'largest_city',
       'official_language', 'continent'],
      dtype='object')

In [ ]:
# sacamos el 'value_counts()'  de cada una de las columnas categóricas que tienen nulos para saber como es la distribución de sus categorías
for col in nulos_categoricas:
    print(f"La distribución de las categorías para la columna {col.upper()}")
    display(df_nulos[col].value_counts() / df_nulos.shape[0])
    print("........................")

La distribución de las categorías para la columna ABBREVIATION

abbreviation
AF    0.005155
PY    0.005155
NE    0.005155
NG    0.005155
KP    0.005155
        ...
GR    0.005155
GD    0.005155
GT    0.005155
GN    0.005155
ZW    0.005155
Name: count, Length: 188, dtype: float64

........................
La distribución de las categorías para la columna CAPITAL/MAJOR_CITY

capital/major_city
Kabul                    0.005155
Tirana                   0.005155
Wellington               0.005155
Managua                  0.005155
Niamey                   0.005155
                           ...
Athens                   0.005155
St. George's, Grenada    0.005155
Guatemala City           0.005155
Conakry                  0.005155
Harare                   0.005155
Name: count, Length: 192, dtype: float64

........................
La distribución de las categorías para la columna CURRENCY-CODE

currency-code
EUR    0.118557
XOF    0.041237
XCD    0.030928
USD    0.030928
XAF    0.025773
         ...
GMD    0.005155
FJD    0.005155
ETB    0.005155
ERN    0.005155
ZMW    0.005155
Name: count, Length: 133, dtype: float64

........................
La distribución de las categorías para la columna LARGEST_CITY

largest_city
S����                    0.010309
Panama City              0.005155
Managua                  0.005155
Niamey                   0.005155
Lagos                    0.005155
                           ...
Macedonia                0.005155
St. George's, Grenada    0.005155
Guatemala City           0.005155
Kankan                   0.005155
Harare                   0.005155
Name: count, Length: 188, dtype: float64

........................
La distribución de las categorías para la columna OFFICIAL_LANGUAGE

official_language
English             0.159794
French              0.128866
Spanish             0.097938
Arabic              0.087629
Portuguese          0.036082
                      ...
Albanian            0.005155
Jamaican English    0.005155
Lao                 0.005155
Latvian             0.005155
Shona               0.005155
Name: count, Length: 76, dtype: float64

........................
La distribución de las categorías para la columna CONTINENT

continent
Africa             0.273196
Europe             0.242268
Asia               0.226804
Central America    0.103093
Oceania            0.072165
South America      0.067010
North America      0.010309
Name: count, dtype: float64

........................

Tras valoración de los datos de cada columna categórica hemos decidido que tipo de método usar con los valores nulos: 

En una lista añadiremos las columnas en las que vamos a utilizar el método unk y en la otra en la que utilizaremos la moda

In [ ]:
columnas_datos_desconocidos= ['abbreviation', 'capital/major_city', 'currency-code', 'largest_city','continent']
columna_datos_moda = 'official_language'

In [ ]:
for col in columnas_datos_desconocidos:
    df_nulos[col] = df_nulos[col].fillna("Unknown")

/tmp/ipykernel_15388/1661505093.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_nulos[col] = df_nulos[col].fillna("Unknown")

Generamos la moda de la única columna que hemos decidido importar con la moda

In [ ]:
moda_language = df_nulos['official_language'].mode()[0]
moda_language

'English'

La aplicamos. No usamos bucle porque solo tenemos una columna

In [ ]:
df_nulos['official_language'] = df_nulos['official_language'].fillna(moda_language)

/tmp/ipykernel_15388/852336255.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_nulos['official_language'] = df_nulos['official_language'].fillna(moda_language)

In [ ]:
df_nulos[columnas_datos_desconocidos].isnull().sum()

abbreviation          0
capital/major_city    0
currency-code         0
largest_city          0
continent             0
dtype: int64

In [ ]:
df_nulos[columna_datos_moda].isnull().sum()

0

In [ ]:
df_nulos.select_dtypes(include='O').sample(10)

,country,abbreviation,capital/major_city,currency-code,largest_city,official_language,continent
179,Turkey,TR,Ankara,TRY,Istanbul,Turkish,Europe
18,Benin,BJ,Porto-Novo,XOF,Cotonou,French,Africa
190,Venezuela,VE,Caracas,VED,Caracas,Spanish,South America
85,Japan,JP,Tokyo,Unknown,Tokyo,English,Asia
106,Malta,MT,Valletta,EUR,Birkirkara,Maltese,Europe
101,Madagascar,MG,Antananarivo,MGA,Antananarivo,French,Africa
193,Zambia,ZM,Lusaka,ZMW,Lusaka,English,Africa
168,Sweden,SE,Stockholm,SEK,S�����,Swedish,Europe
104,Maldives,MV,Mal�,Unknown,Mal�,Divehi,Asia
165,Sri Lanka,LK,Colombo,LKR,Colombo,Tamil,Asia

He visto que hemos imputado el idioma inglés como lengua oficial a Japón....

### IMPUTACIONES EN COLUMNAS NUMÉRICAS

In [ ]:
columnas_numericas = df_nulos.select_dtypes(include=[int,float])
columnas_numericas

,density,agricultural_land,land_area,armed_forces_size,birth_rate,calling_code,co2-emissions,cpi,cpi_change,fertility_rate,forested_area,gasoline_price,gdp,gross_primary_education_enrollment,gross_tertiary_education_enrollment,infant_mortality,life_expectancy,maternal_mortality_ratio,minimum_wage,out_of_pocket_health_expenditure,physicians_per_thousand,population,population_labor_force_participation,tax_revenue,total_tax_rate,unemployment_rate,urban_population,latitude,longitude
0,60.0,58.1,652.230,323.0,32.49,93.0,8.672,149.90,2.3,4.47,2.1,0.70,1.910135e+10,104.0,9.7,47.9,64.5,638.0,0.43,78.4,0.28,NaN,48.9,9.3,71.4,11.12,NaN,33.939110,67.709953
1,105.0,43.1,28.748,9.0,11.78,355.0,4.536,119.05,1.4,1.62,28.1,1.36,1.527808e+10,107.0,55.0,7.8,78.5,15.0,1.12,56.9,1.20,NaN,55.7,18.6,36.6,12.33,NaN,41.153332,20.168331
2,18.0,17.4,NaN,317.0,24.28,213.0,150.006,151.36,2.0,3.02,0.8,0.28,1.699882e+11,109.9,51.4,20.1,76.7,112.0,0.95,28.1,1.72,NaN,41.2,37.2,66.1,11.70,NaN,28.033886,1.659626
3,164.0,40.0,468.000,NaN,7.20,376.0,469.000,NaN,NaN,1.27,34.0,1.51,3.154058e+09,106.4,NaN,2.7,NaN,NaN,6.63,36.4,3.33,77.142,NaN,NaN,NaN,NaN,67.873,42.506285,1.521801
4,26.0,47.5,NaN,117.0,40.73,244.0,34.693,261.73,17.1,5.52,46.3,0.97,9.463542e+10,113.5,9.3,51.6,60.8,241.0,0.71,33.4,0.21,NaN,77.5,9.2,49.1,6.89,NaN,-11.202692,17.873887
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
190,32.0,24.5,912.050,343.0,17.88,58.0,164.175,NaN,254.9,2.27,52.7,0.00,4.823593e+11,97.2,79.3,21.4,72.1,125.0,0.01,45.8,1.92,NaN,59.7,NaN,73.3,8.80,NaN,6.423750,-66.589730
191,314.0,39.3,331.210,522.0,16.75,84.0,192.668,163.52,2.8,2.05,48.1,0.80,2.619212e+11,110.6,28.5,16.5,75.3,43.0,0.73,43.5,0.82,NaN,77.4,19.1,37.6,2.01,NaN,14.058324,108.277199
192,56.0,44.6,527.968,40.0,30.45,967.0,10.609,157.58,8.1,3.79,1.0,0.92,2.691440e+10,93.6,10.2,42.9,66.1,164.0,NaN,81.0,0.31,NaN,38.0,NaN,26.6,12.91,NaN,15.552727,48.516388
193,25.0,32.1,752.618,16.0,36.19,260.0,5.141,212.31,9.2,4.63,65.2,1.40,2.306472e+10,98.7,4.1,40.4,63.5,213.0,0.24,27.5,1.19,NaN,74.6,16.2,15.6,11.43,NaN,-13.133897,27.849332
194,38.0,41.9,390.757,51.0,30.68,263.0,10.983,105.51,0.9,3.62,35.5,1.34,2.144076e+10,109.9,10.0,33.9,61.2,458.0,NaN,25.8,0.21,NaN,83.1,20.7,31.6,4.95,NaN,-19.015438,29.154857

In [ ]:
# Obtenemos la lista de columnas numéricas que tienen nulos
nulos_numericas = df_nulos[df_nulos.columns[df_nulos.isnull().any()]].select_dtypes(include = np.number).columns
print("Las columnas numéricas que tienen nulos son : \n ")
print(nulos_numericas)

Las columnas numéricas que tienen nulos son :

Index(['agricultural_land', 'land_area', 'armed_forces_size', 'birth_rate',
       'co2-emissions', 'cpi', 'cpi_change', 'fertility_rate', 'forested_area',
       'gasoline_price', 'gdp', 'gross_primary_education_enrollment',
       'gross_tertiary_education_enrollment', 'infant_mortality',
       'life_expectancy', 'maternal_mortality_ratio', 'minimum_wage',
       'out_of_pocket_health_expenditure', 'physicians_per_thousand',
       'population', 'population_labor_force_participation', 'tax_revenue',
       'total_tax_rate', 'unemployment_rate', 'urban_population', 'latitude',
       'longitude'],
      dtype='object')

División entre el total de filas: / df_nulos.shape[0] devuelve el número de filas en el DataFrame df_nulos. 

Al dividir la cantidad de valores nulos por el número total de filas, se obtiene el porcentaje de valores nulos en cada columna.

In [ ]:
df_nulos[['agricultural_land', 'land_area', 'armed_forces_size', 'birth_rate',
    'co2-emissions', 'cpi', 'cpi_change', 'fertility_rate', 'forested_area',
    'gasoline_price', 'gdp', 'gross_primary_education_enrollment',
    'gross_tertiary_education_enrollment', 'infant_mortality',
    'life_expectancy', 'maternal_mortality_ratio', 'minimum_wage',
    'out_of_pocket_health_expenditure', 'physicians_per_thousand',
    'population', 'population_labor_force_participation', 'tax_revenue',
    'total_tax_rate', 'unemployment_rate', 'urban_population', 'latitude',
    'longitude']].isnull().sum() / df_nulos.shape[0]

agricultural_land                       0.030928
land_area                               0.149485
armed_forces_size                       0.144330
birth_rate                              0.025773
co2-emissions                           0.056701
cpi                                     0.097938
cpi_change                              0.077320
fertility_rate                          0.030928
forested_area                           0.030928
gasoline_price                          0.097938
gdp                                     0.005155
gross_primary_education_enrollment      0.030928
gross_tertiary_education_enrollment     0.056701
infant_mortality                        0.025773
life_expectancy                         0.036082
maternal_mortality_ratio                0.067010
minimum_wage                            0.226804
out_of_pocket_health_expenditure        0.030928
physicians_per_thousand                 0.030928
population                              0.798969
population_labor_force_participation    0.092784
tax_revenue                             0.128866
total_tax_rate                          0.056701
unemployment_rate                       0.092784
urban_population                        0.768041
latitude                                0.005155
longitude                               0.005155
dtype: float64

In [ ]:
df_nulos_numericos = df_nulos[['agricultural_land', 'land_area', 'armed_forces_size', 'birth_rate',
    'co2-emissions', 'cpi', 'cpi_change', 'fertility_rate', 'forested_area',
    'gasoline_price', 'gdp', 'gross_primary_education_enrollment',
    'gross_tertiary_education_enrollment', 'infant_mortality',
    'life_expectancy', 'maternal_mortality_ratio', 'minimum_wage',
    'out_of_pocket_health_expenditure', 'physicians_per_thousand',
    'population', 'population_labor_force_participation', 'tax_revenue',
    'total_tax_rate', 'unemployment_rate', 'urban_population', 'latitude',
    'longitude']]

In [ ]:
df_nulos_numericos.describe().T

,count,mean,std,min,25%,50%,75%,max
agricultural_land,188.0,3.911755e+01,2.178305e+01,6.000000e-01,2.170000e+01,3.960000e+01,5.537500e+01,8.260000e+01
land_area,165.0,2.552127e+02,2.583850e+02,0.000000e+00,4.127700e+01,1.484600e+02,4.300000e+02,9.640000e+02
armed_forces_size,166.0,1.037831e+02,1.671580e+02,0.000000e+00,1.025000e+01,2.850000e+01,1.282500e+02,9.360000e+02
birth_rate,189.0,2.021497e+01,9.945774e+00,5.900000e+00,1.130000e+01,1.795000e+01,2.875000e+01,4.608000e+01
co2-emissions,183.0,1.259155e+02,1.817949e+02,1.016000e+00,7.600000e+00,3.447700e+01,1.850305e+02,7.279730e+02
cpi,175.0,1.441936e+02,5.478400e+01,9.903000e+01,1.136700e+02,1.247400e+02,1.559250e+02,5.509300e+02
cpi_change,179.0,6.722346e+00,2.445041e+01,-4.300000e+00,1.000000e+00,2.300000e+00,4.250000e+00,2.549000e+02
fertility_rate,188.0,2.698138e+00,1.282267e+00,9.800000e-01,1.705000e+00,2.245000e+00,3.597500e+00,6.910000e+00
forested_area,188.0,3.201543e+01,2.379133e+01,0.000000e+00,1.100000e+01,3.200000e+01,4.817500e+01,9.830000e+01
gasoline_price,175.0,1.002457e+00,3.688585e-01,0.000000e+00,7.550000e-01,9.800000e-01,1.240000e+00,2.000000e+00
gdp,193.0,4.772959e+11,2.172173e+12,4.727146e+07,8.454620e+09,3.438723e+10,2.340940e+11,2.142770e+13
gross_primary_education_enrollment,188.0,1.024702e+02,1.315161e+01,2.340000e+01,9.895000e+01,1.025500e+02,1.080250e+02,1.425000e+02
gross_tertiary_education_enrollment,183.0,3.796339e+01,2.926102e+01,8.000000e-01,1.215000e+01,3.120000e+01,6.315000e+01,1.366000e+02
infant_mortality,189.0,2.133280e+01,1.954806e+01,1.400000e+00,6.000000e+00,1.400000e+01,3.270000e+01,8.450000e+01
life_expectancy,187.0,7.227968e+01,7.483661e+00,5.280000e+01,6.700000e+01,7.320000e+01,7.750000e+01,8.540000e+01
maternal_mortality_ratio,181.0,1.603923e+02,2.335020e+02,2.000000e+00,1.300000e+01,5.300000e+01,1.860000e+02,1.150000e+03
minimum_wage,150.0,2.194133e+00,2.970796e+00,1.000000e-02,4.025000e-01,1.045000e+00,2.447500e+00,1.359000e+01
out_of_pocket_health_expenditure,188.0,3.263723e+01,1.917270e+01,2.000000e-01,1.745000e+01,3.070000e+01,4.397500e+01,8.160000e+01
physicians_per_thousand,188.0,1.839840e+00,1.684261e+00,1.000000e-02,3.325000e-01,1.460000e+00,2.935000e+00,8.420000e+00
population,39.0,3.335427e+02,2.964675e+02,1.008400e+01,8.713000e+01,2.150560e+02,5.561625e+02,9.735600e+02
population_labor_force_participation,176.0,6.273807e+01,1.050291e+01,3.800000e+01,5.615000e+01,6.245000e+01,6.950000e+01,8.680000e+01
tax_revenue,169.0,1.657396e+01,6.961632e+00,0.000000e+00,1.170000e+01,1.630000e+01,2.110000e+01,3.720000e+01
total_tax_rate,183.0,4.082240e+01,2.055766e+01,8.000000e+00,3.060000e+01,3.720000e+01,4.800000e+01,2.196000e+02
unemployment_rate,176.0,6.886364e+00,5.079216e+00,9.000000e-02,3.395000e+00,5.360000e+00,9.490000e+00,2.818000e+01
urban_population,45.0,2.794610e+02,2.833224e+02,5.464000e+00,4.076500e+01,1.790390e+02,4.177650e+02,9.848120e+02
latitude,193.0,1.902572e+01,2.400607e+01,-4.090056e+01,4.535277e+00,1.718988e+01,4.014310e+01,6.496305e+01
longitude,193.0,2.015471e+01,6.688082e+01,-1.751982e+02,-8.224454e+00,2.093944e+01,4.851639e+01,1.780650e+02

#### REVISIÓN VALORES CONTINUOS

In [ ]:
columnas_medianas = ['agricultural_land', 'birth_rate', 'cpi', 'fertility_rate', 'forested_area',
 'gross_primary_education_enrollment', 'gross_tertiary_education_enrollment',
 'life_expectancy', 'out_of_pocket_health_expenditure',
 'physicians_per_thousand', 'population_labor_force_participation',
 'tax_revenue', 'latitude', 'longitude']

Aplicamos la mediana en las columnas numéricas con valores que no tienen gran diferencia entre la media y la mediana.

In [ ]:
df_nulos[columnas_medianas] = df_nulos[columnas_medianas].fillna(df_nulos[columnas_medianas].median())

In [ ]:
df_nulos[columnas_medianas].describe().T

,count,mean,std,min,25%,50%,75%,max
agricultural_land,194.0,39.132474,21.441945,0.600000,22.425000,39.600000,54.925000,82.600000
birth_rate,194.0,20.156598,9.822690,5.900000,11.425000,17.950000,28.542500,46.080000
cpi,194.0,142.288351,52.339567,99.030000,114.445000,124.740000,151.315000,550.930000
fertility_rate,194.0,2.684124,1.264627,0.980000,1.710000,2.245000,3.567500,6.910000
forested_area,194.0,32.014948,23.418597,0.000000,11.325000,32.000000,47.725000,98.300000
gross_primary_education_enrollment,194.0,102.472680,12.945572,23.400000,99.325000,102.550000,107.575000,142.500000
gross_tertiary_education_enrollment,194.0,37.579897,28.458168,0.800000,12.625000,31.200000,61.400000,136.600000
life_expectancy,194.0,72.312887,7.348708,52.800000,67.375000,73.200000,77.275000,85.400000
out_of_pocket_health_expenditure,194.0,32.577320,18.875318,0.200000,17.650000,30.700000,43.775000,81.600000
physicians_per_thousand,194.0,1.828093,1.659185,0.010000,0.355000,1.460000,2.882500,8.420000
population_labor_force_participation,194.0,62.711340,10.001500,38.000000,57.125000,62.450000,68.300000,86.800000
tax_revenue,194.0,16.538660,6.495770,0.000000,12.525000,16.300000,20.350000,37.200000
latitude,194.0,19.016257,23.944163,-40.900557,4.544175,17.189877,40.124603,64.963051
longitude,194.0,20.158756,66.707350,-175.198242,-7.941496,20.939444,48.281523,178.065032

Comparamos visualmente las medias de los DataFrame antes y después de imputar los valores nulos y comprobamos que la media se mantiene practicamente intacta.

In [ ]:
df_nulos[columnas_medianas].isnull().sum()

agricultural_land                       0
birth_rate                              0
cpi                                     0
fertility_rate                          0
forested_area                           0
gross_primary_education_enrollment      0
gross_tertiary_education_enrollment     0
life_expectancy                         0
out_of_pocket_health_expenditure        0
physicians_per_thousand                 0
population_labor_force_participation    0
tax_revenue                             0
latitude                                0
longitude                               0
dtype: int64

#### REVISIÓN VALORES ATÍPICOS

In [13]:
columnas_atipicas = ['land_area','armed_forces_size','co2-emissions', 'cpi_change', 'gasoline_price','gdp',
                    'infant_mortality','maternal_mortality_ratio','minimum_wage','population','total_tax_rate',
                    'unemployment_rate','urban_population']

In [20]:
df_nulos[columnas_atipicas].value_counts()

land_area  armed_forces_size  co2-emissions  cpi_change  gasoline_price  gdp           infant_mortality  maternal_mortality_ratio  minimum_wage  population  total_tax_rate  unemployment_rate  urban_population
2.586      2.0                8.988           1.7        1.19            7.110492e+10  1.9               5.0                       13.05         645.397     20.4            5.36               565.488             1
4.033      1.0                543.000         1.1        1.02            1.981846e+09  16.7              58.0                      0.68          483.628     37.5            12.25              364.029             1
13.812     12.0               2.017           2.6        1.16            5.494737e+09  2.3               6.0                       1.23          622.137     22.2            14.88              417.765             1
13.880     1.0                1.786           2.5        0.92            1.282700e+10  8.3               70.0                      5.25          389.482     33.8            10.36              323.784             1
18.274     4.0                2.046           1.8        0.82            5.535549e+09  21.6              34.0                      1.28          889.953     32.1            4.10               505.048             1
22.966     2.0                568.000        -0.9        1.13            1.879614e+09  11.2              36.0                      1.65          390.353     31.1            6.41               179.039             1
38.394     6.0                1.261           2.7        0.98            2.446674e+09  24.8              183.0                     0.32          727.145     35.3            2.34               317.538             1
214.969    3.0                2.384           2.1        0.90            4.280444e+09  25.1              169.0                     0.98          782.766     30.6            11.85              208.912             1
316.000    2.0                1.342           1.6        1.36            1.478616e+10  6.1               6.0                       5.07          502.653     44.0            3.47               475.902             1
430.000    1.0                1.276           4.1        1.81            5.209000e+09  11.3              27.0                      3.13          287.025     35.6            10.33              89.431              1
Name: count, dtype: int64

In [21]:
df_nulos[columnas_atipicas].isnull().sum()

land_area                    29
armed_forces_size            28
co2-emissions                11
cpi_change                   15
gasoline_price               19
gdp                           1
infant_mortality              5
maternal_mortality_ratio     13
minimum_wage                 44
population                  155
total_tax_rate               11
unemployment_rate            18
urban_population            149
dtype: int64

In [24]:
df_nulos.shape

(194, 36)

Hay dos columnas con gran cantidad de valores nulos. Necesitamos calcular el porcentaje de nulos para valorar su eliminación

In [25]:
df_nulos['population'].isnull().mean()*100

79.89690721649485

In [26]:
df_nulos['urban_population'].isnull().mean()*100

76.80412371134021

Son porcentajes altos, elimninamos estas dos columnas en nuestro DataFrame de origen

In [28]:
df_nulos = df_nulos.drop(['population','urban_population'], axis = 1)

Comprobamos hemos eliminado correctamente estas columnas

In [30]:
df_nulos.shape

(194, 34)

#### Análisis de correlacciones esperadas en estas columnas con valores atípicos

Aplicaremos el método KNN en función de esto

In [31]:
from sklearn.impute import KNNImputer

In [32]:
df_KNN = df_nulos.copy()

#### land_area (área terrestre)

Se relaciona con: agricultural_land (tierra agrícola), forested_area (área forestal), population (más tierra puede permitir mayor población).

In [33]:
knn_imputer = KNNImputer(n_neighbors=5)

vecinas = ['agricultural_land', 'forested_area']

df_KNN[['land_area']] = knn_imputer.fit_transform(df_KNN[['land_area']])

In [42]:
df_KNN['land_area'].describe().T

count    194.000000
mean     255.212661
std      238.182902
min        0.000000
25%       52.546250
50%      239.785500
75%      341.036250
max      964.000000
Name: land_area, dtype: float64

In [43]:
df_nulos['land_area'].describe().T

count    165.000000
mean     255.212661
std      258.385008
min        0.000000
25%       41.277000
50%      148.460000
75%      430.000000
max      964.000000
Name: land_area, dtype: float64

####  armed_forces_size (tamaño de fuerzas armadas)

Se relaciona con: gdp (PIB alto permite mayor inversión en defensa), population (más población puede significar más soldados disponibles).

In [39]:
vecinas = ['gdp']

df_KNN[['armed_forces_size']] = knn_imputer.fit_transform(df_KNN[['armed_forces_size']])

In [40]:
df_KNN[['armed_forces_size']].describe().T

,count,mean,std,min,25%,50%,75%,max
armed_forces_size,194.0,103.783133,154.557671,0.0,12.25,42.0,104.695783,936.0

In [41]:
df_nulos[['armed_forces_size']].describe().T

,count,mean,std,min,25%,50%,75%,max
armed_forces_size,166.0,103.783133,167.158031,0.0,10.25,28.5,128.25,936.0

####  co2-emissions (emisiones de CO₂)

Se relaciona con: gdp (economías más grandes suelen emitir más CO₂), population (más gente genera más consumo y emisiones).

In [44]:
vecinas = ['gdp']

df_KNN[['co2-emissions']] = knn_imputer.fit_transform(df_KNN[['co2-emissions']])

In [45]:
df_KNN[['co2-emissions']].describe().T

,count,mean,std,min,25%,50%,75%,max
co2-emissions,194.0,125.91547,176.538233,1.016,8.0735,41.089,167.79375,727.973

In [46]:
df_nulos[['co2-emissions']].describe().T

,count,mean,std,min,25%,50%,75%,max
co2-emissions,183.0,125.91547,181.794917,1.016,7.6,34.477,185.0305,727.973

Sobreescribo la columna en el DF original alcomprobar los datos

In [47]:
df_nulos[['co2-emissions']]= df_KNN[['co2-emissions']]


   
   

    cpi_change (cambio en inflación, IPC)

Se relaciona con: gdp (el crecimiento económico afecta la inflación), minimum_wage (los salarios afectan el poder adquisitivo).

    gasoline_price (precio de gasolina)

Se relaciona con: gdp (economías más ricas pueden tener subsidios o impuestos distintos), tax_revenue (mayor carga fiscal puede subir precios).

    gdp (Producto Interno Bruto)

Se relaciona con: population (más gente puede significar más producción), co2-emissions (economías industriales emiten más).

    infant_mortality (mortalidad infantil)

Se relaciona con: life_expectancy (países con alta mortalidad infantil suelen tener menor esperanza de vida), maternal_mortality_ratio (problemas de salud materno-infantil están ligados).

    maternal_mortality_ratio (mortalidad materna)

Se relaciona con: physicians_per_thousand (más médicos por habitante reducen la mortalidad), out_of_pocket_health_expenditure (gasto en salud puede afectar la calidad de la atención médica).

    minimum_wage (salario mínimo)

Se relaciona con: gdp (países más ricos tienden a tener salarios más altos), cpi (inflación puede afectar el poder adquisitivo).

    total_tax_rate (tasa total de impuestos)

Se relaciona con: gdp (países con mayor PIB pueden tener tasas más estructuradas), tax_revenue (recaudación fiscal depende de los impuestos).

    unemployment_rate (tasa de desempleo)

Se relaciona con: gdp (economías más fuertes suelen tener menos desempleo), population_labor_force_participation (cuántas personas buscan trabajo activamente).

In [ ]:
imputer_iterative = IterativeImputer(max_iter = 20, random_state = 42)

# ajustamos y tranformamos los datos
imputer_iterative_imputado = imputer_iterative.fit_transform(columnas_atipicas)

# comprobamos que es lo que nos devuelve, que en este caso es un array también
imputer_iterative_imputado

ValueError: could not convert string to float: 'land_area'

In [ ]:
imputer_knn = KNNImputer(n_neighbors = 5)

# ajustamos y transformamos los datos
imputer_knn_imputado = imputer_knn.fit_transform(df_nulos_numericos)

# comprobamos que es lo que nos devuelve, que sigue siendo un array
imputer_knn_imputado

array([[ 58.1     , 652.23    , 323.      , ..., 574.7288  ,  33.93911 ,
         67.709953],
       [ 43.1     ,  28.748   ,   9.      , ..., 527.6378  ,  41.153332,
         20.168331],
       [ 17.4     , 145.1964  , 317.      , ..., 672.6548  ,  28.033886,
          1.659626],
       ...,
       [ 44.6     , 527.968   ,  40.      , ..., 654.7376  ,  15.552727,
         48.516388],
       [ 32.1     , 752.618   ,  16.      , ..., 654.7376  , -13.133897,
         27.849332],
       [ 41.9     , 390.757   ,  51.      , ..., 574.7288  , -19.015438,
         29.154857]])

Informe: Añade al final de un jupyter una explicación breve que describa las columnas que tenían valores nulos, cómo decidiste imputarlos y cualquier observación adicional que consideres importante sobre el proceso de limpieza de datos.

Nota: Puedes utilizar cualquier método o estrategia de imputación que consideres adecuado para los datos y discutir las ventajas y desventajas de tu elección en el informe.